discovery:
  # Key used to group endpoints by clusters
  # meta_cluster_key: "CLUSTER"
  consul_sd_config:
    server: localhost:8500
    tag_separator: ','
    scheme: https
    allow_stale: true
    refresh_interval: 30s
    tags:
    - aerospike
client_config:
  ### AUTH ### 
  # Enable authentication
  auth_enabled: true
  # Use external authentication (https://docs.aerospike.com/docs/guide/security/access-control.html#external-authentication-with-ldap)
  auth_external: true
  # Env variable to use to retrieve the credentials and env
  username_env: "AEROSPIKE_USERNAME"
  password_env: "AEROSPIKE_PASSWORD"
  ### TLS ###
  # Tag to use in the discovery to determine wether or not the probe should connect to cluster in SSL
  tls_tag: "tls"
  # Meta key to find the tls-hostname to use for SSL cert validation
  tls_hostname_meta_key: "tls-hostname"
  # Skip ssl verification
  tls_skip_verify: false 
  ### Probe discovery configuration ###
  # The key prefix to discover Aerospike's namespaces through service discovery
  namespace_meta_key_prefix: "aerospike-monitoring-"
  ### Probe configuration ###
  monitoring_set: monitoring
  latency_key_prefix: monitoring_latency_
  durability_key_prefix: monitoring_durability_
  durability_key_total: 10000 # Number of keys to generate for the durability check
  ### Client connection configuration ###
  connection_queue_size: 2 # Avoid creating too many connections. We don't need many as we duplicate the clients many times
  opening_connection_threshold: 30
  min_connections_per_node: 2
  exit_fast_on_exhausted_connection_pool: True
checks_configs:
  latency_check:
    enable: true
    interval: 500ms
  durability_check:
    enable: true
    interval: 600s
